### ISSUE TITLE
Add python scripts to predict runtime

### ISSUE THREAD

**Issue by idanyani** [technion-csl/mosmodel#12]
We should provide our users a convenient interface for predicting the runtime with all available models.
I recommend to create a new "scripts" folder and have a separate script per model, something like:

```
> ./scripts/predictGandhi.py -m <M>
> ./scripts/predictPoly3.py -c <C>
> ./scripts/predictMosmodel.py -h <H> -c <C> -m <M>
```

Each script should implicitly read its coefficients file (located under ./analysis) and fail if this file isn't there.
Additionally, it would be great if the scripts raise a warning when the given inputs fall out of the training range; this feature would require us to save the range in a separate file for later use.

**Comment by magbarya** [comment]
Added Basu, Pham, Gandhi, Yaniv, Alam, Polynomial (of degree=1,2,3), and mosmodel predictors to the "predictors" directory.
