### ISSUE TITLE
Generating mosmodel for partial run of the program

### ISSUE THREAD

**Issue by akshaybaviskar** [technion-csl/mosmodel#2]
Hello,

A few of my workloads run in two phases: 1. generate the input 2. Run an algorithm on the generated input.
Generating input mostly has a very low TLB miss rate.
So, I am interested only in analyzing the second part of the benchmark.
However, the mosmodel would be generated based on page walk cycles, TLB miss rate, and execution cycles observed for the complete run of the program.

I suppose that if somehow I can choose to run perf only for the partial run of the program then the resulting mosmodel would also represent the partial run of the program.

Could you please give me some pointers on how can I implement this?

Thanks,
Akshay

**Comment by idanyani** [comment]
@akshaybaviskar : please see the new commit and let us know if this is what you need.
The top level makefile now takes the benchmark as an input via the $BENCHMARK_PATH environment variable.
[$BENCHMARK_PATH defaults to some toy benchmark that is part of the repository, so if you run "make" without specifying the benchmark you will run mosmodel on our toy benchmark (which takes ~30 seconds).]

$BENCHMARK_PATH should be a path to a directory with the following files in it:
(1) pre_run.sh - a script running before the "actual" benchmark is measured.
(2) run.sh - the main script of the benchmark which will be measured with perf.
(3) post_run.sh - a script running after the "actual" benchmark is measured.

Can you split your benchmark into three scripts as described above?

**Comment by akshaybaviskar** [comment]
@idanyani 
Sorry, I couldn't go through it yesterday as I was caught up in another project.

I am not sure how can I split my benchmark into three scripts.
Since my benchmark is a single binary file. The two phases I mentioned are part of the single program.

e.g. my_benchmark.cpp looks like this:

> read_input_file_and_generate_graph( );
> create_a_file_to_indicate_that_input_is_ready( );
> 
> sleep(1); //wait for the polling script to ATTACH perf tool to this pid
> 
> run_graph_algorithm( );  //actual benchmark
> 
> create_a_file_to_indicate_that_algorithm_is_finished( );
> sleep(1); //wait for the polling script to STOP perf tool attached to this pid
> 
> run_rest_of_the_benchmark( );
> 

my polling script looks like this:
It takes PID of the benchmark to be polled as input.
> while [ ! -f /tmp/input_ready ]; do
>             sleep 0.05
> done
> 
> perf stat -p $BM_PID -e mem_inst_retired.all_loads:u,mem_inst_retired.all_stores:u,mem_inst_retired.stlb_miss_loads:u,mem_inst_retired.stlb_miss_stores:u 2> $PERFOP
> 
> PERF_PID=$!
> 
> while [ ! -f /tmp/algorithm_done ]; do
>             sleep 0.05
> done
> 
> kill -INT $PERF_PID
> 

Please let me know if something is not clear.

**Comment by idanyani** [comment]
@akshaybaviskar: thanks for describing your benchmark structure.

Unfortunately, our code doesn't support benchmarks like you described because we assume that the benchmark is unaware of it (== the benchmark) being measured by an external program. This assumption seems reasonable to us because this is how a lot of benchmarks are implemented, e.g., SPEC CPU2017, Graph500, HPCC, etc.
Are you using a well-known benchmark? If so, can you please provide us with its name and, if available, a link to the source code?

**Comment by akshaybaviskar** [comment]
@idanyani 
I am using benchmarks which were used in vMitosis (ASPLOS'21) paper.
"Fast Local Page-Tables for Virtualized NUMA Servers with vMitosis"
Here is the link to the workloads :
https://github.com/mitosis-project/vmitosis-workloads

You can see the described structure here:
https://github.com/mitosis-project/vmitosis-workloads/blob/25b5ede02e6e5cfe9dc05e5cae5d904bc64006ff/btree/btree.c#L1570

I looked into this script a little bit and I understand that the perf command is ran using this script measureGeneralMetrics.sh, input to this script is the benchmark along with setting up the parameters for mosalloc. 
I am thinking that instead of taking benchmark as input, if I run this script in parallel, which takes input as pid of the benchmark and then starts measuring metrics when the file is created. Will it be possible?
I can give it a try.

**Comment by idanyani** [comment]
Yes, I guess that you can modify the measureGeneralMetrics.sh script to take the PID as input and attach perf to this PID. Please let us know if it worked for you.

**Comment by idanyani** [comment]
Hi @akshaybaviskar : can you please update us? Can we close this issue?

**Comment by idanyani** [comment]
Closing this issue as per @akshaybaviskar 's request.
