### ISSUE TITLE
Use ram size instead of MMAP_POOL_LIMIT

### ISSUE THREAD

**Issue by magbarya** [technion-csl/mosmodel#20]
The mosmodel pool sizes are calculated by running the memory_footprint experiment, which uses the RAM size as the initial brk pool size and MMAP_POOL_LIMIT as the initial mmap pool size then it calculates the exact sizes. 
RAM size could be used as well for the mmap pool size for the memory_footprint, instead of the MMAP_POOL_LIMIT. check if this is true, and if so use the RAM size instead as done for the brk pool size.

**Comment by idanyani** [comment]
@magbarya I think we can close this issue, right?

**Comment by magbarya** [comment]
Fixed by f9acb1325ee422c36b6636f95cbd7f493925aa6f
