### ISSUE TITLE
Error while running make on new benchmark

### ISSUE THREAD

**Issue by akshaybaviskar** [technion-csl/mosmodel#4]
@magbarya @idanyani 

I ran the make command with the latest changes.
I set my run.sh, pre_run.sh and post_run.sh in the same way as done in toy_benchmark.
Below is the log of the error which I got. 
I see that perf count collection for some of the configs was successful, but it failed for one of the configs. 

> ========== [INFO] start producing: experiments/single_page_size/layout4kb/repeat4/perf.out ==========
> creating a new output directory /home/akshaybavisk/work/mosmodel/experiments/single_page_size/layout4kb/repeat4/ ...
> copying the benchmark files to /home/akshaybavisk/work/mosmodel/experiments/single_page_size/layout4kb/repeat4/...
> warming up before running...
> running the benchmark /home/akshaybavisk/work/vmitosis-workloads/bin/gups...
> the full submit command is:
> 	/home/akshaybavisk/work/mosmodel/scripts/measureGeneralMetrics.sh /home/akshaybavisk/work/mosmodel/scripts/setCpuMemoryAffinity.sh 1 	/home/akshaybavisk/work/mosmodel/mosalloc/runMosalloc.py --library /home/akshaybavisk/work/mosmodel/mosalloc/src/libmosalloc.so  -fps 1GB -aps 104857600 -as1 0 -ae1 0 -as2 0 -ae2 0 -bps 182251520 -bs1 0 -be1 0 -bs2 0 -be2 0 --analyze ./run.sh
> waiting for the run to complete...
> sleeping a bit to let the filesystem recover...
> validating the run outputs...
> cleaning large files from the output directory...
> syncing to clean all pending I/O activity...
> ARGS_FOR_MOSALLOC=" -fps 1GB -aps 104857600 -as1 0 -ae1 0 -as2 0 -ae2 0 -bps 182251520 -bs1 0 -be1 0 -bs2 0 -be2 0"
> /home/akshaybavisk/work/mosmodel/scripts/runBenchmark.py --exclude_files=perf.data \
> 	--submit_command "perf record --data --count=$(( 2**15 )) --event=mem_inst_retired.stlb_miss_loads:p,mem_inst_retired.stlb_miss_stores:p -- /home/akshaybavisk/work/mosmodel/mosalloc/runMosalloc.py --analyze $ARGS_FOR_MOSALLOC --library /home/akshaybavisk/work/mosmodel/mosalloc/src/libmosalloc.so" \
> 	/home/akshaybavisk/work/vmitosis-workloads/bin/gups experiments/pebs_tlb_miss_trace/repeat0/
> creating a new output directory /home/akshaybavisk/work/mosmodel/experiments/pebs_tlb_miss_trace/repeat0/ ...
> copying the benchmark files to /home/akshaybavisk/work/mosmodel/experiments/pebs_tlb_miss_trace/repeat0/...
> warming up before running...
> running the benchmark /home/akshaybavisk/work/vmitosis-workloads/bin/gups...
> the full submit command is:
> 	perf record --data --count=32768 --event=mem_inst_retired.stlb_miss_loads:p,mem_inst_retired.stlb_miss_stores:p -- /home/akshaybavisk/work/mosmodel/mosalloc/runMosalloc.py --analyze  -fps 1GB -aps 104857600 -as1 0 -ae1 0 -as2 0 -ae2 0 -bps 182251520 -bs1 0 -be1 0 -bs2 0 -be2 0 --library /home/akshaybavisk/work/mosmodel/mosalloc/src/libmosalloc.so ./run.sh
> waiting for the run to complete...
> Traceback (most recent call last):
>   File "/home/akshaybavisk/work/mosmodel/scripts/runBenchmark.py", line 103, in <module>
>     benchmark_run.wait()
>   File "/home/akshaybavisk/work/mosmodel/scripts/runBenchmark.py", line 51, in wait
>     raise subprocess.CalledProcessError(self._run_process.returncode, ' '.join(self._run_process.args))
> subprocess.CalledProcessError: Command 'perf record --data --count=32768 --event=mem_inst_retired.stlb_miss_loads:p,mem_inst_retired.stlb_miss_stores:p -- /home/akshaybavisk/work/mosmodel/mosalloc/runMosalloc.py --analyze -fps 1GB -aps 104857600 -as1 0 -ae1 0 -as2 0 -ae2 0 -bps 182251520 -bs1 0 -be1 0 -bs2 0 -be2 0 --library /home/akshaybavisk/work/mosmodel/mosalloc/src/libmosalloc.so ./run.sh' returned non-zero exit status 255.
> make: *** [experiments/pebs_tlb_miss_trace/module.mk:15: experiments/pebs_tlb_miss_trace/repeat0/perf.data] Error 1

**Comment by akshaybaviskar** [comment]
@magbarya @idanyani 
I rebooted the system and ran the make command for gups benchmark. 
The complete output log can be seen here [make_gups.log](https://github.com/technion-csl/mosmodel/files/6701443/make_gups.log)

It looks to me that it ran for 34 different configuration before failing due to the following error:
```
analysis/pebs_tlb_miss_trace/findWeightedWindow.py --input_file=analysis/pebs_tlb_miss_trace/mem_bins_4kb.csv --output_file=analysis/pebs_tlb_miss_trace/hot_region_4kb.txt --memory_footprint=$mem_footprint --page_size=4KB
analysis/pebs_tlb_miss_trace/findWeightedWindow.py:86: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if max_access_start_page is -1:
Input file does not contain page accesses information about the specified pool!
make: *** [analysis/pebs_tlb_miss_trace/module.mk:38: analysis/pebs_tlb_miss_trace/hot_region_4kb.txt] Error 1
```

Can you please check this?
Also, I have two questions:
1. How many samples does this tool generate? Is it the same as the 54 samples mentioned in the paper?
2. Which all models does this tool generate? Where can I check the coefficients for the generated model(s)?

Thanks!

**Comment by magbarya** [comment]
Hi Akshay,
Regarding your questions:
1) Yes, it's 54 samples, the same as specified in the paper.
2) You need to run "make mosmodel", which builds the Mosmodel and calculates its max-error. Then, you can use the content of the "analysis/mosmodel/my_models.py"  script alongside the train/test datasets under analysis/mosmodel to build your model. I can write a short script that reads the model inputs from the user, uses the train/test sets, and outputs the expected runtime.

Regarding the failure you got:
There is a warning (python SyntaxWarning) that was already fixed, and there is another error that fails the make: "Input file does not contain page accesses information about the specified pool!". This error means that Intel PEBS could not capture TLB-misses events for your running workload, which seems weird if you run on Skylake.
Can you please double check and send us the CPU model of the platform you are using to run your experiments on it.
Besides that, I appreciate if you could attach the following files:
experiments/pebs_tlb_miss_trace/repeat0/perf.data
analysis/pebs_tlb_miss_trace/mem_bins_4kb.csv
experiments/pebs_tlb_miss_trace/repeat0/pools_base_pointers.out

**Comment by akshaybaviskar** [comment]
Hi Mohammad,

Please find the requested files attached. I have renamed these files ( added .txt) to allow uploading here. Please rename again after downloading.
[mem_bins_4kb.csv](https://github.com/technion-csl/mosmodel/files/6708257/mem_bins_4kb.csv)
[perf_data.txt](https://github.com/technion-csl/mosmodel/files/6708283/perf_data.txt)
[pools_base_pointers_out.txt](https://github.com/technion-csl/mosmodel/files/6708284/pools_base_pointers_out.txt)

My CPU model is Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz (SkyLake Architecture)
I use the following perf counters to calculate TLB Miss Rate on it :
```
Total accesses = mem_inst_retired.all_loads:u + mem_inst_retired.all_stores:u
Total misses = mem_inst_retired.stlb_miss_loads:u + mem_inst_retired.stlb_miss_stores:u

```
I will run with the latest commit and see if I get any errors.
In experiments/growing_window_2m/layout1/repeat2/perf.out ( [perf_out.txt](https://github.com/technion-csl/mosmodel/files/6708476/perf_out.txt) ), I see that you are using dtlb_store_misses.miss_causes_a_walk and dtlb_store_misses.miss_causes_a_walk to count the total number of misses. But I don't see the counter which would give the total number of references to DTLB. Can you please check?

Thanks!

**Comment by magbarya** [comment]
Hi Akshay,
Can you please rerun the PEBS experiment?
First, please clean the previous run bu running:
make experiments/pebs_tlb_miss_trace/clean analysis/pebs_tlb_miss_trace/clean
and then rerun by typing:
make analysis/pebs_tlb_miss_trace

If that does not work for you, please re-attach the same files you attached previously.

Thanks!

**Comment by magbarya** [comment]
Hi Akshay,
Can you still reproduce this issue? If not, please let us know so we can close it.

**Comment by akshaybaviskar** [comment]
Yes, we can close this issue. Thanks.
