### ISSUE TITLE
Run make clean before every new benchmark?

### ISSUE THREAD

**Issue by akshaybaviskar** [technion-csl/mosmodel#6]
@idanyani @magbarya 

Do I need to run make clean every time before running make for a new benchmark?

If I just update the benchmark path in benchmark.mk and then run the make command, then it would skip the run saying that the output directory already exists. 
Also, this means that for every benchmark the output is written in the same directory. Can we instead save the output in the benchmark-specific directory (e.g. the path mentioned in the benchmark.mk)? This way the data remains saved for future purposes.

Thanks,
Akshay

**Comment by magbarya** [comment]
Hi Akshay,
For now, the simplest way to do that is by cloning the repository for each benchmark to a separated directory and run "make" for the specific directory.
We might add support to the makefile (or may add a new makefile) for building multiple benchmarks.

**Comment by akshaybaviskar** [comment]
Oh, yes! That's the easy way. Thanks :)
