### ISSUE TITLE
pandas.Index.contains() is deprecated 

### ISSUE THREAD

**Issue by idanyani** [technion-csl/mosmodel#9]
@akshaybaviskar encountered the following issue when running:

$ analysis/arrangeDataToPlot.py --normalize='by-y' --y-metric='cpu-cycles' \
--mean_file=results/growing_window_2m/mean.csv --output=analysis/growing_window_2m/normalized_scatter.csv
Traceback (most recent call last):
  File "analysis/arrangeDataToPlot.py", line 55, in <module>
    output_df = readSingle(mean_file, std_file, args.y_metric, args.x_metric)
  File "analysis/arrangeDataToPlot.py", line 31, in readSingle
    mean_df[x_metric] = metric_func(mean_ps)
  File "/home/akshaybavisk/work/mosmodel_gups/analysis/performance_statistics.py", line 31, in getWalkDuration
    walk_duration = self.__getWalkCounter(index, 'active')
  File "/home/akshaybavisk/work/mosmodel_gups/analysis/performance_statistics.py", line 21, in __getWalkCounter
    if self._df.columns.contains(load_counter) \
AttributeError: 'Index' object has no attribute 'contains'
make: *** [analysis/common.mk:43: analysis/growing_window_2m/normalized_scatter.csv] Error 1

The problem is that pandas.Index.contains() is now deprecated:
https://pandas.pydata.org/pandas-docs/version/0.25.3/reference/api/pandas.Index.contains.html

**Comment by magbarya** [comment]
Fixed in [8293236](https://github.com/technion-csl/mosmodel/commit/8293236e4b08bcd9a974560ff1f8a2355688fb7c)

**Comment by magbarya** [comment]
Replace the use of "pandas.Index.contains()" with "in" to look for a key in pandas dataframe
